# Generated by Django 6.0.3 on 2026-10-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('COLLEGE', 'College / University'), ('PSU', 'Public Sector Undertaking'), ('INDUSTRY', 'Industrial Estate'), ('MUNICIPAL', 'Municipal Campus')], default='HOSPITAL', max_length=50)),
                ('category_label', models.CharField(default='Institutional Estate', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('area_sqft', models.BigIntegerField(default=1000000)),
                ('occupancy_current', models.IntegerField(default=5000)),
                ('occupancy_max', models.IntegerField(default=10000)),
                ('assigned_admin_name', models.CharField(max_length=255)),
                ('assigned_admin_email', models.EmailField(max_length=254, unique=True)),
                ('assigned_password', models.CharField(default='estate@2026', max_length=255)),
                ('iot_gateway_ip', models.GenericIPAddressField(default='192.168.1.1')),
                ('iot_status', models.CharField(default='ONLINE', max_length=50)),
                ('sustainability_score', models.IntegerField(default=85)),
                ('carbon_target_reduction_pct', models.IntegerField(default=25)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(default='Operational', max_length=50)),
                ('health_score', models.IntegerField(default=95)),
                ('power_rating_kw', models.FloatField(default=50.0)),
                ('runtime_hours_today', models.FloatField(default=14.0)),
                ('vibration_mm_per_sec', models.FloatField(default=1.2)),
                ('operating_temp_c', models.FloatField(default=45.0)),
                ('last_calibrated', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('data_source', models.CharField(default='IoT LAN/WiFi', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_load_kw', models.FloatField(default=850.0)),
                ('daily_total_kwh', models.FloatField(default=18000.0)),
                ('peak_load_kw', models.FloatField(default=1100.0)),
                ('grid_power_kw', models.FloatField(default=650.0)),
                ('solar_rooftop_kw', models.FloatField(default=200.0)),
                ('power_factor', models.FloatField(default=0.98)),
                ('carbon_emissions_kg', models.FloatField(default=12000.0)),
                ('savings_inr_today', models.FloatField(default=15000.0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_telemetry', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=255)),
                ('bin_type', models.CharField(default='Dry Waste', max_length=100)),
                ('fill_percentage', models.IntegerField(default=50)),
                ('battery_pct', models.IntegerField(default=95)),
                ('predicted_overflow_mins', models.IntegerField(default=120)),
                ('status', models.CharField(default='Normal', max_length=50)),
                ('last_emptied', models.CharField(default='2 hrs ago', max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dustbins', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AqiTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_aqi', models.IntegerField(default=80)),
                ('status', models.CharField(default='Moderate', max_length=50)),
                ('pm25', models.FloatField(default=28.0)),
                ('pm10', models.FloatField(default=65.0)),
                ('co2', models.FloatField(default=500.0)),
                ('voc', models.FloatField(default=120.0)),
                ('temperature', models.FloatField(default=26.0)),
                ('humidity', models.FloatField(default=55.0)),
                ('noise', models.FloatField(default=50.0)),
                ('hotspot_location', models.CharField(default='Main Campus Gateway', max_length=255)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aqi_telemetry', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AiRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('urgency', models.CharField(default='Suggested', max_length=50)),
                ('impact_description', models.TextField()),
                ('estimated_saving', models.CharField(max_length=255)),
                ('confidence_score', models.IntegerField(default=95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slots', models.IntegerField(default=500)),
                ('occupied_slots', models.IntegerField(default=350)),
                ('available_slots', models.IntegerField(default=150)),
                ('ev_charging_total', models.IntegerField(default=40)),
                ('ev_charging_occupied', models.IntegerField(default=28)),
                ('occupancy_rate_pct', models.IntegerField(default=70)),
                ('peak_congestion_zone', models.CharField(default='Main Entry Gateway', max_length=255)),
                ('entry_flow_rate', models.IntegerField(default=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_telemetry', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WaterTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_consumption_kl', models.FloatField(default=400.0)),
                ('flow_rate_lps', models.FloatField(default=18.0)),
                ('underground_tank_level_pct', models.IntegerField(default=80)),
                ('overhead_tank_level_pct', models.IntegerField(default=75)),
                ('stp_recycle_rate_pct', models.IntegerField(default=80)),
                ('stp_treated_water_kl', models.FloatField(default=280.0)),
                ('ph_level', models.FloatField(default=7.3)),
                ('turbidity_ntu', models.FloatField(default=2.0)),
                ('leak_alert_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_telemetry', to='api.organization')),
            ],
        ),
    ]
