# Generated by Django 6.0.3 on 2026-10-08 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='staff@2026', max_length=255)),
                ('role', models.CharField(default='ESTATE_MANAGER', max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('last_active', models.CharField(default='Recently assigned', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.organization')),
            ],
        ),
    ]
