# Generated by Django 6.0.3 on 2026-10-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='campus_image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='campus_nodes_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
