# Generated by Django 6.0.3 on 2026-10-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_campus_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='assigned_admin_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
